services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "50051:50051"
    networks:
      - microservices_network
    volumes:
      - ./protos:/protos

  order_service:
    build:
      context: ./order_service
    ports:
      - "50052:50052"
    networks:
      - microservices_network
    volumes:
      - ./protos:/protos

networks:
  microservices_network:
    driver: bridge