version: '3.8'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "50051:50051"
    networks:
      - microservices_network

  order_service:
    build:
      context: ./order_service
    ports:
      - "50052:50052"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
