services:
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - microservices_network

  order_service:
    build:
      context: .
      dockerfile: ./order_service/Dockerfile
    ports:
      - "50052:50052"
    networks:
      - microservices_network

  payment_service:
    build:
      context: ./payment_service
    ports:
      - "50053:50053"
    networks:
      - microservices_network
    volumes:
      - ./protos:/protos

networks:
  microservices_network:
    driver: bridge